spring.application.name=ad-management
spring.datasource.url=jdbc:mysql://localhost:3306/ad_management_db
spring.datasource.username=rohan
spring.datasource.password=ronnie

spring.jpa.hibernate.ddl-auto=update

jwt.secret=B3dE5fG7hI9jK1lM2nO4pQ6rS8tU0vWE
jwt.expiration=86400000